/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlobalConfirmDialog: typeof import('./components/GlobalConfirmDialog.vue')['default']
    GlobalSnackbar: typeof import('./components/GlobalSnackbar.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./components/ThemeSwitcher.vue')['default']
  }
}
